### ISSUE TITLE
Setting the number of channels for a Buffer

### ISSUE THREAD

**Issue by karamellpelle** [kcat/alure#21]
If I load a file into a Buffer, is it possible to set the number of channels for this Buffer regardless of the number of channels in the file (or is this a feature which could be implemented?)?

Because according to the [OpenAL reference](https://www.openal.org/documentation/openal-1.1-specification.pdf)(_5.3.4. Specifying Buffer Content_), "Buffers containing audio data with more than one channel will be played without 3D spatialization features – these formats are normally used for background music.". If we had this feature, it would be easy to define a sound as a 2D or 3D sound for any file.

**Comment by kcat** [comment]
`Source` objects have the `set3DSpatialize` method. Given the `AL_SOFT_source_spatialize` extension (available since OpenAL Soft 1.18), that allows 3D spatialization to be applied regardless of the buffer's channel count; the sound will be dynamically downmixed to mono and panned as expected when not placed exactly on the listener. You can also force spatialization off, so even mono sounds avoid panning, distance attenuation, and doppler effects. Or set to auto (default), it behaves like standard OpenAL.

This way avoids having to potentially load the file twice with the extra buffer management (one for stereo/multichannel, and another for the mono copy). It also doesn't have to be concerned with unnecessary conversions (e.g. stereo to 5.1).

**Comment by karamellpelle** [comment]
This seems to be the solution - thanks!
