### ISSUE TITLE
Why does Alure have different include files and which files should we use?

### ISSUE THREAD

**Issue by SeanTolstoyevski** [kcat/alure#45]
Hi,

There are multiple C++ files in the "include" folder in Alure's source. (In https://github.com/kcat/alure/tree/master/inclu)
But when I download it from the site, only include alure.h in the include folder. (Https://kcat.strangesoft.net/alure-releases/alure-1.2-win32-bin.zip)
Msys64-mingw-w64 / mingw-w32 also contains only the alure.h file.
Can you say why this difference is caused?

I want to use Alure to get rid of some of the functions of OpenAL.
However, when I examine the source on GitHub, I see that Alure provides a wrapper for OpenAL. And it is written in C++.
There are different files in the download links on the site and different files in GitHub source.

How can we decide which include folder we should use?

In addition:
There is no **win64 dll** in the download link.
I was able to install 64bit of the library with msys64.
There is no 64bit DLL in the download link.

And finally:
How can I compile the sample codes in the examples folder?
I could not get out of this problem. I have defined alure32 and openal32 to G++.
Please enter a note about how we can compile samples in the "example" folder for OpenAL-soft and alure?
Such a note would be great in Readme.
I couldn't find any notes on how these examples could be compiled.
G++ shows errors like **"__imp___xxxx"**.

**Comment by McSinyx** [comment]
Hi @SeanTolstoyevski, the website is obsolete now since it's still describing alure 1 while this repo is for alure 2. Since alure 2 is not released (see GH-44), I don't think we should expect pre-compiled binary although following the instructions in README (building using CMake) works out for me on GNU/Linux, macOS as well as Windows.  Full disclosure: I'm maintaining a Python library depending on alure 2 and I build it on Travis and AppVoyer for CI/CD (see [links on the sidebar](https://mcsinyx.github.io/palace/html/)).

**Comment by SeanTolstoyevski** [comment]
I have browsed  your project and it looks great.
But it cannot be installed on Windows right now.

I think you need to upload Windows dependencies on the repo for this.
It is difficult to find and compile dependencies in Windows.

good lucks.

And topic 2:
I was never aware of this. I didn't know there were 2 alures.
Thanks, I get it now.
